In [2]:
import pandas as pd

In [3]:
url = "https://en.wikipedia.org/wiki/List_of_cities_in_Los_Angeles_County,_California"
dfs = pd.read_html(url, header=0)

lacounty = dfs[0]
lacounty = lacounty[['City','Population as of (2010 Census)']]
lacounty

                     City  Population as of (2010 Census)
0            Agoura Hills                           20330
1                Alhambra                           83089
2                 Arcadia                           56364
3                 Artesia                           16522
4                  Avalon                            3728
5                   Azusa                           46361
6            Baldwin Park                           75390
7                    Bell                           35477
8            Bell Gardens                           42072
9              Bellflower                           76616
10          Beverly Hills                           34109
11               Bradbury                            1048
12                Burbank                          103340
13              Calabasas                           23058
14                 Carson                           91714
15               Cerritos                           49041
16              Claremont                           34926
17               Commerce                           12823
18                Compton                           96455
19                 Covina                           47796
20                 Cudahy                           23805
21            Culver City                           38883
22            Diamond Bar                           55544
23                 Downey                          111772
24                 Duarte                           21321
25               El Monte                          113475
26             El Segundo                           16654
27                Gardena                           58829
28               Glendale                          191719
29               Glendora                           50073
..                    ...                             ...
58   Palos Verdes Estates                           13438
59              Paramount                           54098
60               Pasadena                          137122
61            Pico Rivera                           62942
62                 Pomona                          149058
63    Rancho Palos Verdes                           41643
64          Redondo Beach                           66748
65          Rolling Hills                            1860
66  Rolling Hills Estates                            8067
67               Rosemead                           53764
68              San Dimas                           33371
69           San Fernando                           23645
70            San Gabriel                           39718
71             San Marino                           13147
72          Santa Clarita                          176320
73       Santa Fe Springs                           16223
74           Santa Monica                           89736
75           Sierra Madre                           10917
76            Signal Hill                           11016
77         South El Monte                           20116
78             South Gate                           94396
79         South Pasadena                           25619
80            Temple City                           35558
81               Torrance                          145438
82                 Vernon                             112
83                 Walnut                           29172
84            West Covina                          106098
85         West Hollywood                           34399
86       Westlake Village                            8270
87               Whittier                           85331

[88 rows x 2 columns]

In [6]:
hvi = pd.read_csv("LA_County_HVI.csv")
hvi.head()

,RegionID,RegionName,State,Metro,CountyName,SizeRank,1996-04,1996-05,1996-06,1996-07,...,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02
0,12447,Los Angeles,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,2,155000.0,154600.0,154400.0,154200.0,...,631500,634600,636300,639300,644700,650800,657000,662100,667000,671000
1,46298,Long Beach,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,33,148800.0,149300.0,149100.0,148400.0,...,554500,558200,561000,564400,569300,574400,578600,580900,582000,583000
2,45457,Glendale,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,121,202400.0,203400.0,204700.0,205400.0,...,773000,775000,776600,780800,788200,794500,798300,803400,811300,816500
3,5534,Lancaster,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,137,92300.0,91700.0,91100.0,90600.0,...,247200,250200,252500,255000,258500,262400,266800,270100,272500,274200
4,40227,Palmdale,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,160,NaN,NaN,NaN,NaN,...,274100,277200,280300,283300,286700,289900,293600,296900,299300,301100